I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script2.rpy", line 1653, in script
    scala "흐으으으..."
Exception: Sayer 'scala' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script2.rpy", line 1653, in script
    scala "흐으으으..."
  File "E:\renpy-8.1.2-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\renpy-8.1.2-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'scala' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.2.23090503
Dimension 1.0
Fri Apr 12 16:39:47 2024
